filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      # We’ll also use a template to make sure the container input is used correctly
      templates:
        - condition:
            equals:
              docker.container.labels.co.elastic.logs/enabled: "true"
          config:
            - type: container
              stream: all
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              processors:
                # Map your custom labels to document fields (so you can search by them)
                - add_fields:
                    target: service
                    fields:
                      name: ${data.docker.container.labels.co.elastic.logs/service}
                      env: ${data.docker.container.labels.co.elastic.logs/env}

# (Optional) enrich with Docker metadata
processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]  
  
setup.kibana:
  host: "http://kibana:5601"

logging.to_files: false
logging.level: debug
logging.selectors: ["autodiscover", "docker", "input"]
