"""initial

Revision ID: 7418db84656c
Revises: 
Create Date: 2025-09-08 09:40:45.585007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7418db84656c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogbrand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('picture_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('catalog_type_id', sa.Integer(), nullable=False),
    sa.Column('catalog_brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_brand_id'], ['catalogbrand.id'], ),
    sa.ForeignKeyConstraint(['catalog_type_id'], ['catalogtype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalogitem')
    op.drop_table('catalogtype')
    op.drop_table('catalogbrand')
    # ### end Alembic commands ###
